package lens

import (
	"reflect"
	"testing"
)

// These tests cover the edges the TREE walks — the hops that turn a flat
// table of Applications or Stages into a shape. They assert against the
// SHIPPED yaml rather than a literal, because the failure they exist to catch
// is a typo'd jsonpath: a path that matches nothing resolves silently to no
// neighbours, which renders as "this object is connected to nothing" rather
// than as a broken pack.

func packNamed(t *testing.T, name string) Pack {
	t.Helper()
	packs, errs := Builtins()
	for _, err := range errs {
		t.Fatalf("builtin packs failed to parse: %v", err)
	}
	for _, p := range packs {
		if p.Name == name {
			return p
		}
	}
	t.Fatalf("builtin pack %q not found", name)
	return Pack{}
}

func hasEdge(p Pack, from, to, via, key string) bool {
	for _, e := range p.Edges {
		if e.From == from && e.To == to && e.Via == via && e.Key == key {
			return true
		}
	}
	return false
}

// edgeBetween returns the one edge declared from->to, failing when the pack
// declares none: a test that silently evaluated the zero Edge would report
// "no values" and look like a broken jsonpath rather than a missing edge.
func edgeBetween(t *testing.T, p Pack, from, to string) Edge {
	t.Helper()
	for _, e := range p.Edges {
		if e.From == from && e.To == to {
			return e
		}
	}
	t.Fatalf("pack %q declares no edge %s -> %s", p.Name, from, to)
	return Edge{}
}

const (
	gvrApps      = "argoproj.io/v1alpha1/applications"
	gvrAppProj   = "argoproj.io/v1alpha1/appprojects"
	gvrAppSets   = "argoproj.io/v1alpha1/applicationsets"
	gvrStages    = "kargo.akuity.io/v1alpha1/stages"
	gvrWarehouse = "kargo.akuity.io/v1alpha1/warehouses"
)

func TestArgoCDPackDeclaresTreeEdges(t *testing.T) {
	p := packNamed(t, "argocd")
	if !hasEdge(p, gvrApps, gvrAppProj, ViaField, ".spec.project") {
		t.Error("applications -> appprojects via .spec.project is missing; an AppProject would list none of the Applications it governs")
	}
	if !hasEdge(p, gvrApps, gvrAppSets, ViaOwnerRef, "") {
		t.Error("applications -> applicationsets via ownerRef is missing; a generated Application would not name its generator")
	}
}

// .spec.project is a bare name and is always present — the API server
// defaults it to "default" — so the path must resolve on a minimal
// Application.
func TestArgoCDProjectEdgeResolves(t *testing.T) {
	p := packNamed(t, "argocd")
	e := edgeBetween(t, p, gvrApps, gvrAppProj)
	app := map[string]any{
		"metadata": map[string]any{"name": "payments-web", "namespace": "argocd"},
		"spec":     map[string]any{"project": "platform"},
	}
	if got := Values(e, app); !reflect.DeepEqual(got, []string{"platform"}) {
		t.Errorf("Values = %q, want [platform]", got)
	}
}

// The ownerRef edge must match on the ApplicationSet's apiVersion and nothing
// else. An Application owned by some other controller is not generated by an
// ApplicationSet and must not claim one.
func TestArgoCDAppSetEdgeMatchesOwnerAPIVersion(t *testing.T) {
	p := packNamed(t, "argocd")
	e := edgeBetween(t, p, gvrApps, gvrAppSets)
	app := map[string]any{"metadata": map[string]any{
		"name": "payments-web",
		"ownerReferences": []any{
			map[string]any{"apiVersion": "example.com/v1", "kind": "Thing", "name": "not-an-appset"},
			map[string]any{"apiVersion": "argoproj.io/v1alpha1", "kind": "ApplicationSet", "name": "tenants"},
		},
	}}
	if got := Values(e, app); !reflect.DeepEqual(got, []string{"tenants"}) {
		t.Errorf("Values = %q, want [tenants]", got)
	}
}

func TestKargoPackDeclaresPipelineEdges(t *testing.T) {
	p := packNamed(t, "kargo")
	if !hasEdge(p, gvrStages, gvrStages, ViaField, ".spec.requestedFreight[*].sources.stages[*]") {
		t.Error("the stage->stage edge is missing; without it there is no promotion DAG to walk")
	}
	if !hasEdge(p, gvrStages, gvrWarehouse, ViaField, ".spec.requestedFreight[*].origin.name") {
		t.Error("the stage->warehouse edge is missing; a pipeline tree would start halfway down")
	}
}

// Fan-in is the case worth proving: requestedFreight is a LIST and
// sources.stages is a list inside it, so a Stage gated on two upstreams must
// yield both. A path that only ever returned the first would look correct on
// every linear pipeline and silently drop half of a real one.
func TestKargoStageEdgeResolvesFanIn(t *testing.T) {
	p := packNamed(t, "kargo")
	up := edgeBetween(t, p, gvrStages, gvrStages)
	origin := edgeBetween(t, p, gvrStages, gvrWarehouse)
	stage := map[string]any{
		"metadata": map[string]any{"name": "prod", "namespace": "kargo-demo"},
		"spec": map[string]any{
			"requestedFreight": []any{
				map[string]any{
					"origin":  map[string]any{"kind": "Warehouse", "name": "app-repo"},
					"sources": map[string]any{"stages": []any{"uat", "staging"}},
				},
			},
		},
	}
	if got := Values(up, stage); !reflect.DeepEqual(got, []string{"uat", "staging"}) {
		t.Errorf("upstream stages = %q, want [uat staging]", got)
	}
	if got := Values(origin, stage); !reflect.DeepEqual(got, []string{"app-repo"}) {
		t.Errorf("origin warehouse = %q, want [app-repo]", got)
	}
}

// A Stage that subscribes straight to a Warehouse has sources.direct: true and
// no sources.stages at all. It must yield no upstream rather than an empty
// string, which would render as a nameless node in the tree.
func TestKargoStageEdgeDirectSubscriptionHasNoUpstream(t *testing.T) {
	p := packNamed(t, "kargo")
	up := edgeBetween(t, p, gvrStages, gvrStages)
	stage := map[string]any{
		"metadata": map[string]any{"name": "dev"},
		"spec": map[string]any{
			"requestedFreight": []any{
				map[string]any{
					"origin":  map[string]any{"kind": "Warehouse", "name": "app-repo"},
					"sources": map[string]any{"direct": true},
				},
			},
		},
	}
	if got := Values(up, stage); len(got) != 0 {
		t.Errorf("upstream stages = %q, want none", got)
	}
}
